# Generated by Django 4.1.1 on 2022-09-17 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='price')),
                ('period', models.CharField(blank=True, choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('Prime', 'Prime'), ('Premium', 'Premium'), ('Free', 'Free')], max_length=20, null=True)),
                ('feature1', models.CharField(blank=True, max_length=30, null=True)),
                ('feature2', models.CharField(blank=True, max_length=30, null=True)),
                ('feature3', models.CharField(blank=True, max_length=30, null=True)),
                ('feature4', models.CharField(blank=True, max_length=30, null=True)),
                ('feature5', models.CharField(blank=True, max_length=30, null=True)),
                ('feature6', models.CharField(blank=True, max_length=30, null=True)),
                ('feature7', models.CharField(blank=True, max_length=30, null=True)),
                ('feature8', models.CharField(blank=True, max_length=30, null=True)),
                ('feature9', models.CharField(blank=True, max_length=30, null=True)),
                ('feature10', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_package', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
