# Generated by Django 4.1.1 on 2022-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='name',
            field=models.CharField(default='one', max_length=30),
            preserve_default=False,
        ),
    ]
