# Generated by Django 4.1.1 on 2022-09-17 09:07

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_packages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
