# Generated by Django 4.1.1 on 2022-09-18 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('period', models.CharField(blank=True, choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('Prime', 'Prime'), ('Premium', 'Premium'), ('Free', 'Free')], max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_package', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
