# Generated by Django 4.1.1 on 2022-09-21 09:17

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.AddField(
            model_name='package',
            name='cctv_devices_apability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='download_speed',
            field=models.CharField(choices=[('3 mbps', '3 mbps'), ('6 mbps', '6 mbps'), ('12 mbps', '12 mbps')], default='ff', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hd_tv_shows',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='heavy_online_gaming_downloading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='heavy_video_downloads',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='internet_surfing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='light_video_downloads',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='multiple_devices',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='online_gaming_live_streams',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='sd_movie_music_streaming',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='unlimited_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='period',
            field=models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], default='ddd', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='type'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Ostrich', 'Ostrich'), ('Eagle', 'Eagle'), ('Falcon', 'Falcon')], default='ddd', max_length=30),
            preserve_default=False,
        ),
    ]
