# Generated by Django 4.1.1 on 2022-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_package_name_package_cctv_devices_apability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(default='rrrr', upload_to='services/'),
            preserve_default=False,
        ),
    ]
