# Generated by Django 4.1.1 on 2023-08-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_service_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="download_speed",
            field=models.CharField(
                choices=[
                    ("3 mbps", "3 mbps"),
                    ("4 mbps", "4 mbps"),
                    ("6 mbps", "6 mbps"),
                    ("10 mbps", "10 mbps"),
                    ("12 mbps", "12 mbps"),
                    ("Custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="type",
            field=models.CharField(
                choices=[
                    ("Tit", "Tit"),
                    ("Sparrow", "Sparrow"),
                    ("Owl", "Owl"),
                    ("Ostrich", "Ostrich"),
                    ("Eagle", "Eagle"),
                    ("Falcon", "Falcon"),
                ],
                max_length=30,
            ),
        ),
    ]
