# Generated by Django 4.1.1 on 2023-11-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_package_download_speed_alter_package_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
