# Generated by Django 4.1.1 on 2023-11-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(max_length=260),
        ),
    ]
