# Generated by Django 4.1.1 on 2023-11-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="download_speed",
            field=models.CharField(
                choices=[
                    ("6 mbps", "6 mbps"),
                    ("8 mbps", "8 mbps"),
                    ("10 mbps", "10 mbps"),
                    ("15 mbps", "15 mbps"),
                    ("Custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
