# Generated by Django 4.1.1 on 2023-11-29 07:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title"
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("Contract", "Contract"), ("Fultime", "Fultime")],
                        max_length=50,
                        verbose_name="Job Type",
                    ),
                ),
                ("location", models.CharField(max_length=50, verbose_name="Location")),
                ("roles", ckeditor.fields.RichTextField()),
                ("skills", ckeditor.fields.RichTextField()),
                ("acedemic_qualification", ckeditor.fields.RichTextField()),
                ("experience", ckeditor.fields.RichTextField()),
                ("deadline", models.DateTimeField(verbose_name="")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
    ]
