# Generated by Django 4.1.1 on 2023-11-30 05:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Career", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="summary",
            field=ckeditor.fields.RichTextField(
                default="To build a world-class developer onboarding and educational platform, that removes the friction and uncertainty that developers face in the transition from web2 to web3, we need to build a team with many different perspectives and experiences. "
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(verbose_name="Deadline"),
        ),
    ]
